// Code generated by entc, DO NOT EDIT.

package checkin

const (
	// Label holds the string label denoting the checkin type in the database.
	Label = "checkin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCheckinTime holds the string denoting the checkin_time field in the database.
	FieldCheckinTime = "checkin_time"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// EdgeSender holds the string denoting the sender edge name in mutations.
	EdgeSender = "sender"
	// Table holds the table name of the checkin in the database.
	Table = "checkins"
	// SenderTable is the table that holds the sender relation/edge.
	SenderTable = "checkins"
	// SenderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SenderInverseTable = "users"
	// SenderColumn is the table column denoting the sender relation/edge.
	SenderColumn = "user_checkins"
)

// Columns holds all SQL columns for checkin fields.
var Columns = []string{
	FieldID,
	FieldCheckinTime,
	FieldEventID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "checkins"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_checkins",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CheckinTimeValidator is a validator for the "checkin_time" field. It is called by the builders before save.
	CheckinTimeValidator func(int64) error
	// EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	EventIDValidator func(string) error
)
