// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"helloworld/ent/checkin"
	"helloworld/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CheckinCreate is the builder for creating a Checkin entity.
type CheckinCreate struct {
	config
	mutation *CheckinMutation
	hooks    []Hook
}

// SetCheckinTime sets the "checkin_time" field.
func (cc *CheckinCreate) SetCheckinTime(i int64) *CheckinCreate {
	cc.mutation.SetCheckinTime(i)
	return cc
}

// SetEventID sets the "event_id" field.
func (cc *CheckinCreate) SetEventID(s string) *CheckinCreate {
	cc.mutation.SetEventID(s)
	return cc
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (cc *CheckinCreate) SetSenderID(id int) *CheckinCreate {
	cc.mutation.SetSenderID(id)
	return cc
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (cc *CheckinCreate) SetNillableSenderID(id *int) *CheckinCreate {
	if id != nil {
		cc = cc.SetSenderID(*id)
	}
	return cc
}

// SetSender sets the "sender" edge to the User entity.
func (cc *CheckinCreate) SetSender(u *User) *CheckinCreate {
	return cc.SetSenderID(u.ID)
}

// Mutation returns the CheckinMutation object of the builder.
func (cc *CheckinCreate) Mutation() *CheckinMutation {
	return cc.mutation
}

// Save creates the Checkin in the database.
func (cc *CheckinCreate) Save(ctx context.Context) (*Checkin, error) {
	var (
		err  error
		node *Checkin
	)
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CheckinMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			if node, err = cc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			if cc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CheckinCreate) SaveX(ctx context.Context) *Checkin {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CheckinCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CheckinCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CheckinCreate) check() error {
	if _, ok := cc.mutation.CheckinTime(); !ok {
		return &ValidationError{Name: "checkin_time", err: errors.New(`ent: missing required field "checkin_time"`)}
	}
	if v, ok := cc.mutation.CheckinTime(); ok {
		if err := checkin.CheckinTimeValidator(v); err != nil {
			return &ValidationError{Name: "checkin_time", err: fmt.Errorf(`ent: validator failed for field "checkin_time": %w`, err)}
		}
	}
	if _, ok := cc.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "event_id"`)}
	}
	if v, ok := cc.mutation.EventID(); ok {
		if err := checkin.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "event_id": %w`, err)}
		}
	}
	return nil
}

func (cc *CheckinCreate) sqlSave(ctx context.Context) (*Checkin, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cc *CheckinCreate) createSpec() (*Checkin, *sqlgraph.CreateSpec) {
	var (
		_node = &Checkin{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: checkin.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: checkin.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.CheckinTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: checkin.FieldCheckinTime,
		})
		_node.CheckinTime = value
	}
	if value, ok := cc.mutation.EventID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: checkin.FieldEventID,
		})
		_node.EventID = value
	}
	if nodes := cc.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkin.SenderTable,
			Columns: []string{checkin.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_checkins = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheckinCreateBulk is the builder for creating many Checkin entities in bulk.
type CheckinCreateBulk struct {
	config
	builders []*CheckinCreate
}

// Save creates the Checkin entities in the database.
func (ccb *CheckinCreateBulk) Save(ctx context.Context) ([]*Checkin, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Checkin, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CheckinCreateBulk) SaveX(ctx context.Context) []*Checkin {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CheckinCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CheckinCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
