// Code generated by entc, DO NOT EDIT.

package ent

import (
	"helloworld/ent/checkin"
	"helloworld/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	checkinFields := schema.Checkin{}.Fields()
	_ = checkinFields
	// checkinDescCheckinTime is the schema descriptor for checkin_time field.
	checkinDescCheckinTime := checkinFields[0].Descriptor()
	// checkin.CheckinTimeValidator is a validator for the "checkin_time" field. It is called by the builders before save.
	checkin.CheckinTimeValidator = checkinDescCheckinTime.Validators[0].(func(int64) error)
	// checkinDescEventID is the schema descriptor for event_id field.
	checkinDescEventID := checkinFields[1].Descriptor()
	// checkin.EventIDValidator is a validator for the "event_id" field. It is called by the builders before save.
	checkin.EventIDValidator = checkinDescEventID.Validators[0].(func(string) error)
}
