// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// EdgeCheckins holds the string denoting the checkins edge name in mutations.
	EdgeCheckins = "checkins"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CheckinsTable is the table that holds the checkins relation/edge.
	CheckinsTable = "checkins"
	// CheckinsInverseTable is the table name for the Checkin entity.
	// It exists in this package in order to avoid circular dependency with the "checkin" package.
	CheckinsInverseTable = "checkins"
	// CheckinsColumn is the table column denoting the checkins relation/edge.
	CheckinsColumn = "user_checkins"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldPhoneNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
